[test]
preload = ["./src/__tests__/setup.ts"]
coverage = true
coverageThreshold = {
  statements = 80,
  branches = 70,
  functions = 80,
  lines = 80
}
timeout = 30000
testMatch = ["**/__tests__/**/*.test.ts"]
testPathIgnorePatterns = ["/node_modules/", "/dist/"]
collectCoverageFrom = [
  "src/**/*.{ts,tsx}",
  "!src/**/*.d.ts",
  "!src/**/*.test.ts",
  "!src/types/**/*",
  "!src/mocks/**/*"
]

[build]
target = "node"
outdir = "./dist"
minify = true
sourcemap = "external"

[install]
production = false
frozen = true
peer = false

[install.cache]
dir = ".bun"
disable = false

[debug]
port = 9229

[env]
# Environment-specific configurations
development.LOG_LEVEL = "debug"
production.LOG_LEVEL = "warn"

[hot]
restart = true
reload = true

[performance]
gc = true
optimize = true 