version: '3.8'

services:
  homeassistant-mcp:
    image: homeassistant-mcp:latest
    environment:
      - ENABLE_SPEECH_FEATURES=${ENABLE_SPEECH_FEATURES:-true}
      - ENABLE_WAKE_WORD=${ENABLE_WAKE_WORD:-true}
      - ENABLE_SPEECH_TO_TEXT=${ENABLE_SPEECH_TO_TEXT:-true}

  fast-whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    volumes:
      - whisper-models:/models
      - audio-data:/audio
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=faster_whisper
      - WHISPER_BEAM_SIZE=5
      - COMPUTE_TYPE=float32
      - LANGUAGE=en
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/asr/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  wake-word:
    image: rhasspy/wyoming-openwakeword:latest
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    group_add:
      - audio
    network_mode: host

volumes:
  whisper-models:
  audio-data:
