name: Deploy MkDocs
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'  # Enable pip caching
      
      - name: Cache MkDocs dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      
      - name: Check links
        run: |
          mkdocs build --strict
          
      - name: Test build
        run: |
          mkdocs build
          if [ ! -d "site" ]; then
            echo "Build failed - site directory not created"
            exit 1
          fi
      
      - name: Deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force
      
      - name: Verify deployment
        run: |
          # Wait for GitHub Pages to update
          sleep 30
          # Check if the site is accessible
          curl -s -f -o /dev/null "https://jango-blockchained.github.io/advanced-homeassistant-mcp" || exit 1 